version: '3.4'

services:

  redis-cluster:
    image: redis-cluster-initializer
    env_file: .env
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      redisnet:

  redis-1:
    image: redis-cluster-node
    env_file: .env
    environment:
      X_REDIS_PORT: 7001
    networks:
      redisnet:
    ports:
      - 7001:7001

  redis-2:
    image: redis-cluster-node
    env_file: .env
    environment:
      X_REDIS_PORT: 7002
    networks:
      redisnet:
    ports:
      - 7002:7002

  redis-3:
    image: redis-cluster-node
    env_file: .env
    environment:
      X_REDIS_PORT: 7003
    networks:
      redisnet:
    ports:
      - 7003:7003

  redis-4:
    image: redis-cluster-node
    env_file: .env
    environment:
      X_REDIS_PORT: 7004
    networks:
      redisnet:
    ports:
      - 7004:7004

  redis-5:
    image: redis-cluster-node
    env_file: .env
    environment:
      X_REDIS_PORT: 7005
    networks:
      redisnet:
    ports:
      - 7005:7005

  redis-6:
    image: redis-cluster-node
    env_file: .env
    environment:
      X_REDIS_PORT: 7006
    networks:
      redisnet:
    ports:
      - 7006:7006

networks:
  redisnet:
    driver: bridge